name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SSH key 생성
        run: |
          echo "${{ secrets.AWS_KEY }}" > was.pem
          chmod 600 was.pem

      - name: 파일 전송
        run: |
          scp -o StrictHostKeyChecking=no -i was.pem 01_front.txt \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/ubuntu/