name: backend deploy

on:
  push:
    branches: [ main ]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x SimpleDmsReact/gradlew

      - name: build
        run: |
          cd SimpleDmsReact
          ./gradlew bootWar

      - name: SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > was.pem
          chmod 600 was.pem

      - name: upload war
        run: |
          scp -o StrictHostKeyChecking=no -i was.pem \
          SimpleDmsReact/build/libs/*.war \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~

      - name: stop backend
        run: |
          ssh -o StrictHostKeyChecking=no -i was.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo fuser -k 8080/tcp || true"

      - name: start backend
        run: |
          ssh -o StrictHostKeyChecking=no -i was.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "nohup java -jar ~/SimpleDmsReact-0.0.1-SNAPSHOT.war > app.log 2>&1 &"