name: backend deploy

on:
  push:
    branches: [ main ]   # main 브랜치에 push 발생 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1) GitHub 소스 다운로드
      - uses: actions/checkout@v4

      # 2) Java 설치
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Spring Boot WAR 빌드1
      - name: Grant execute permission
        run: chmod +x SimpleDmsReact/gradlew

      # 3) Spring Boot WAR 빌드2
      - name: build
        run: |
          cd SimpleDmsReact
          ./gradlew bootWar

      # 4) SSH key 생성
      - name: SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > was.pem
          chmod 600 was.pem

      # 5) WAR 업로드
      - name: upload war
        run: |
          scp -o StrictHostKeyChecking=no -i was.pem \
          SimpleDmsReact/build/libs/*.war \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~

      # 6) 기존 서버 종료
      - name: stop backend
        run: |
          ssh -o StrictHostKeyChecking=no -i was.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} pkill -f war || true

      # 7) 서버 시작
      - name: start backend
        run: |
          ssh -o StrictHostKeyChecking=no -i was.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} nohup java -jar ~/SimpleDmsReact-0.0.1-SNAPSHOT.war > app.log 2>&1 &